### ISSUE TITLE
build regression in quicklisp 2012-12-23: unbound variable +CM-LINK+

### ISSUE THREAD

**Issue by avodonosov** [flambard/CLERIC#6]
In quicklisp 2012-12-23 cleric fails to build on some lisps like CCL, ACL, wile on the previous quicklisp it build on these lisps OK.

Check the library test-grid page: http://common-lisp.net/project/cl-test-grid/library/cleric.html
Click the failure links to open the build logs.

Some examples:
ACL: http://cl-test-grid.appspot.com/blob?key=1001268
CCL: http://cl-test-grid.appspot.com/blob?key=973288

**Comment by flambard** [comment]
Thanks for reporting this!

I have fixed the issues with undefined constants.

**Comment by avodonosov** [comment]
Unfortunately it still have unbound variable error, but now with  COMMON-LISP-ERLANG-INTERFACE::+PASS-THROUGH+.  Check various lisps here: http://common-lisp.net/project/cl-test-grid/library/cleric.html

**Comment by flambard** [comment]
Fixed and included in the 2013 april update of Quicklisp.
